select = ["ALL"]
target-version = "py312"
line-length = 100
ignore = [
    "E501", # https://docs.astral.sh/ruff/rules/line-too-long/
    "D", # https://docs.astral.sh/ruff/rules/#pydocstyle-d
    "COM812", # https://docs.astral.sh/ruff/rules/missing-trailing-comma/
    "ISC001", # https://docs.astral.sh/ruff/rules/single-line-implicit-string-concatenation/
]

[format]
quote-style = "double"
indent-style = "space"
