line-length = 100

[lint]
# See https://docs.astral.sh/ruff/rules/
select = ["C4", "D2", "D3", "D4", "E", "F", "I"]
ignore = ["D202", "D205", "D206", "D400", "D404", "E402", "E501", "E703"]
fixable = ["I"]

[lint.pydocstyle]
convention = "numpy"
